import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:provider/provider.dart';
import 'core/themes/app_theme.dart';
import 'data/models/milk_entry.dart';
import 'data/models/expense_entry.dart';
import 'logic/providers/dairy_provider.dart';
import 'features/expense/expense_provider.dart';
import 'ui/screens/home_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive
  await Hive.initFlutter();

  // Register Adapter (Generated by build_runner)
  // Note: We need to run build_runner for this to exist.
  // If it doesn't exist yet, we might get analysis errors, but we will fix that.
  Hive.registerAdapter(MilkEntryAdapter());
  Hive.registerAdapter(ExpenseEntryAdapter());
  Hive.registerAdapter(ExpenseCategoryAdapter());

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => DairyProvider()..init()),
        ChangeNotifierProvider(create: (_) => ExpenseProvider()..init()),
      ],
      child: MaterialApp(
        title: 'Dairy Manager',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.lightTheme,
        home: const HomeScreen(),
      ),
    );
  }
}
